mark = new Array("","","","o","","o","","o","","o","","","8","","","o","","o","","o","","o","","","8");

pos0 = new Array("off","on","off","on","off","red","on","off","on","off","on","off","on","on","off","off","off","on","on","off","red","off","on","off","on","on","off","on");
pos1 = new Array("off","on","on","off","on","off","red","on","off","on","off","on","off","on","off","off","on","off","on","on","off","red","off","on","off","on","on","off");
pos2 = new Array("off","off","on","on","off","on","off","red","on","off","on","off","on","off","off","off","off","on","off","on","on","off","red","off","on","off","on","on");
pos3 = new Array("off","on","off","on","on","off","on","off","red","on","off","on","off","on","off","off","on","off","on","off","on","on","off","red","off","on","off","on");
pos4 = new Array("off","off","on","off","on","on","off","on","off","red","on","off","on","off","off","off","on","on","off","on","off","on","on","off","red","off","on","off");
pos5 = new Array("off","on","off","on","off","on","on","off","on","off","red","on","off","on","off","off","off","on","on","off","on","off","on","on","off","red","off","on");
pos6 = new Array("off","off","on","off","on","off","on","on","off","on","off","red","on","off","off","off","on","off","on","on","off","on","off","on","on","off","red","off");
pos7 = new Array("off","on","off","on","off","on","off","on","on","off","on","off","red","on","off","off","off","on","off","on","on","off","on","off","on","on","off","red");
pos8 = new Array("off","red","on","off","on","off","on","off","on","on","off","on","off","red","off","off","red","off","on","off","on","on","off","on","off","on","on","off");
pos9 = new Array("off","off","red","on","off","on","off","on","off","on","on","off","on","off","off","off","off","red","off","on","off","on","on","off","on","off","on","on");
pos10 = new Array("off","on","off","red","on","off","on","off","on","off","on","on","off","on","off","off","on","off","red","off","on","off","on","on","off","on","off","on");
pos11 = new Array("off","off","on","off","red","on","off","on","off","on","off","on","on","off","off","off","on","on","off","red","off","on","off","on","on","off","on","off");

var index = parent.ScaleSelect.document.ScaleFinder.scales.selectedIndex

document.write('<table cellpadding=0 cellspacing=0><tr>');

for (i=0;i<mark.length;i++)
{
 document.write('<td align=center><font size=-2></font>'+mark[i]+'</td>');
}

document.write('</tr><tr>');

document.write('<td><img src="nut_'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td></tr><tr>');

document.write('<td><img src="nut_'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td></tr><tr>');

document.write('<td><img src="nut_'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td></tr><tr>');

document.write('<td><img src="nut_'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td>');
document.write('</tr><tr>');

document.write('<td><img src="nut_'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td></tr><tr>');

document.write('<td><img src="nut_'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td><td><img src="'+pos1[index]+'.jpg"></td><td><img src="'+pos2[index]+'.jpg"></td><td><img src="'+pos3[index]+'.jpg"></td><td><img src="'+pos4[index]+'.jpg"></td><td><img src="'+pos5[index]+'.jpg"></td><td><img src="'+pos6[index]+'.jpg"></td><td><img src="'+pos7[index]+'.jpg"></td><td><img src="'+pos8[index]+'.jpg"></td><td><img src="'+pos9[index]+'.jpg"></td><td><img src="'+pos10[index]+'.jpg"></td><td><img src="'+pos11[index]+'.jpg"></td><td><img src="'+pos0[index]+'.jpg"></td></tr><tr>');

document.write('</tr></table>');